# Generated by Django 5.1.4 on 2024-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commuinity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
