# Generated by Django 5.1.4 on 2024-12-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commuinity", "0003_remove_course_is_paid_remove_note_video_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="course",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
